config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  root to: "home#index"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers, :similar_users
    end
  end
  
  resources :posts do
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :favorites, only: [:index]
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
  
  validates_uniqueness_of :post_id, scope: :user_id
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_post, only: [:create, :destroy]
  
  def index
    @favorites = current_user.favorites.includes(:post)
  end
  
  def create
    @favorite = Favorite.create(user_id: current_user.id, post_id: params[:post_id])
  end
  
  def destroy
    favorite = Favorite.find_by(user_id: current_user.id, post_id: params[:post_id])
    favorite.destroy
  end
  
  private

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
  <% unless @post.favorite_user(current_user.id).blank? %>
    <%= link_to post_favorite_path(post_id: @post.id, id: @post.favorites[0].id), method: :delete, remote: true do %>
      <i class="fa-solid fa-heart"></i>
      <%= @post.favorites.count %>
    <% end %>
  <% else %>
    <%= link_to post_favorites_path(@post.id), method: :post, remote: true do %>
      <i class="fa-regular fa-heart"></i>
      <%= @post.favorites.count %>
    <% end %>
  <% end %>
<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post, favorite: @favorite}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons<%= @post.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {post: @post, favorite: @favorite}) %>");

app/views/favorites/index.html.erb
<section class="hero has-background-grey">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        いいね一覧
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% @favorites.each do |favorite| %>
        <%= render partial: 'posts/post', locals: { post: favorite.post } %>
      <% end %>
    </div>
  </div>
</section>