config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  root to: "home#index"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers, :similar_users
    end
  end
  
  resources :posts do
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :favorites, only: [:index]
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:create, :destroy]
  
  def create
    following = current_user.relationships.build(follower_id: params[:user_id])
    following.save
    
  end
  
  def destroy
    following = current_user.relationships.find_by(follower_id: params[:user_id])
    following.destroy
    
  end
  
  private

  def set_user
    @user = User.find(params[:user_id])
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_relationship.html.erb
<% if @user.is_followed_by?(current_user) %>
  <%= link_to "フォロー解除", user_relationships_path(@user), method: :delete, remote: true, class: "button is-danger" %>
<% else %>
  <%= link_to "フォロー", user_relationships_path(@user), method: :post, remote: true, class: "button is-info" %>
<% end %>

app/views/relationships/_relationship_count.html.erb
<%= link_to @user.followings.count, followings_user_path(@user) %>フォロー
<%= link_to @user.followers.count, followers_user_path(@user) %>フォロワー

app/views/relationships/create.js.erb
$('#relationship_<%= @user.id %>').html("<%= j(render partial: 'relationships/relationship', locals: { user: @user }) %>");
$("#relationship_count").html("<%= j(render 'relationships/relationship_count', locals: { user: @user }) %>");

app/views/relationships/destroy.js.erb
$('#relationship_<%= @user.id %>').html("<%= j(render partial: 'relationships/relationship', locals: { user: @user }) %>");
$("#relationship_count").html("<%= j(render 'relationships/relationship_count', locals: { user: @user }) %>");