config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  root to: "home#index"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers, :similar_users
    end
  end
  
  resources :posts do
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :favorites, only: [:index]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :post_images, dependent: :destroy
  accepts_attachments_for :post_images, attachment: :image, append: :true
  
  CATEGORIES = ["アウター", "トップス", "ボトムス", "シューズ", "アクセサリー", "その他"]
  
  with_options presence: true do
    validates :item
    validates :body
    validates :post_images
  end
  
  def favorite_user(user_id)
    favorites.find_by(user_id: user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :post_find, { only:[:show, :edit, :update, :destroy]}
  before_action :authenticate_user!, except: [:index, :show]
  
  def index
    @q = Post.ransack(params[:q])
    @posts = @q.result(distinct: true).includes(:user, :post_images).order(created_at: :desc).page(params[:page]).per(8)
  end


  def show
  end

  def new
    @post = Post.new
  end
  
  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      redirect_to post_path(@post), notice: "投稿しました"
    else
      render "new"
    end
  end

  def edit
    if @post.user != current_user
      redirect_to posts_path, alert: "不正なアクセスです"
    end
  end
  
  def update
    if @post.update(post_params)
    redirect_to post_path(@post), notice: "更新しました"
    else
      render "edit"
    end
  
  end
  
  def destroy
    @post.destroy
    redirect_to posts_path
  end
  
  private
  
  def post_find
    @post = Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:item, :body, :category, post_images_images: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-10">
        <%= form_for @post do |f| %>
          <div class="field">
            <%= f.label :item, "アイテム", class: "label" %>
            <%= f.text_field :item, class: "input" %>
          </div>
          <div class="field">
            <%= f.label :category, "カテゴリー", class: "label" %>
            <%= f.select :category, Post::CATEGORIES, { prompt: "カテゴリーを選択してください" }, { class: 'form-control' } %>
          </div>
          <div class="field">
            <%= f.label :body, "アイテム詳細", class: "label" %>
            <%= f.text_area :body, class: "textarea", value: @post.persisted? ? @post.body : "サイズ: \n着丈: \n袖丈: \n身幅: \n総丈: \nその他詳細: " %>
          </div>
          <% if @post.post_images.any? %>
            <div class="field">
              <%= f.label :item_images, "アイテム画像", class: "label" %>
              <div class="current-images">
                <% @post.post_images.each do |image| %>
                  <%= attachment_image_tag(image, :image, :fill, 50, 50) %>
                <% end %>
              </div>
                <%= f.attachment_field :post_images_images, multiple: true, class: "input" %>
            </div>
          <% else %>
            <div class="field">
              <%= f.label :item_images, "アイテム画像", class: "label" %>
              <%= f.attachment_field :post_images_images, multiple: true, class: "input" %>
            </div>
          <% end %>
          <%= f.submit "投稿", class: "button is-success" %>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/posts/_post.html.erb
<div class="column is-3">
  <div class="card">
    <div class="card-image">
      <figure class="image is-4by3">
        <% post.post_images.first(1).each do |post_image| %>
          <%= link_to post_path(post) do %>
            <%= attachment_image_tag post_image, :image %>
          <% end %>
        <% end %>
      </figure>
    </div>
    <div class="card-content">
      <%= link_to post.item, post_path(post) %>
    </div>
    <div class="card-content">
      <div class="media">
        <div class="media-left">
          <figure class="image is-48x48">
            <%= attachment_image_tag post.user, :profile_image, :fill, 1000, 1000, fallback: "no-image.png", class: "profile_image" %>
          </figure>
        </div>
        <div class="media-content">
          <div class="title"><%= link_to post.user.username, user_path(post.user) %></div>
        </div>
      </div>
      <div class="content">
        <time><%= post.updated_at.strftime("%Y年-%m月-%d日 %H:%M") %></time>
      </div>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<section class="hero has-background-grey">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿編集
      </h1>
    </div>
  </div>
</section>

<%= render 'form' %>

app/views/posts/index.html.erb
<section class="hero has-background-grey">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿一覧
      </h1>
    </div>
  </div>
</section>
<section class="form-section">
  <div class="container">
    <div class="search-form">
      <%= search_form_for @q do |f| %>
        <div class="field">
          <%= f.label :item_cont %>
          <%= f.search_field :item_cont %>
          <%= f.submit "検索", class: "button is-success" %>
        </div>
      <% end %>
    </div>
  </div>
</section>
<section class="section">
  <div class="container">
    <div class="columns is-multiline">
      <% if params[:q] %>
        <% if @posts.present? %>
          <%= render partial: 'posts/post', collection: @posts %>
        <% else %>
          <strong class="no-mach">該当するアイテムが見つかりませんでした</strong>
        <% end %>
      <% else %>
        <%= render partial: 'posts/post', collection: @posts %>
      <% end %>
    </div>
  </div>
</section>

<div class="row" id="paginate">
  <div class="col-md-2">
    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<section class="hero has-background-grey">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        新規投稿
      </h1>
    </div>
  </div>
</section>

<%= render 'form' %>

app/views/posts/show.html.erb
<section class="hero has-background-grey">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        投稿詳細
      </h1>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5">
        <div class="card">
          <div class="card-image">
            <figure class="image" id="slider">
              <% @post.post_images.each do |image| %>
                <%= attachment_image_tag image, :image %>
              <% end %>
            </figure>
          </div>
        </div>
      </div>
      <div class="column is-1"></div>
      <div class="column is-5">
        <div class="card">
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="title is-4"><%= @post.item %></p>
              </div>
            </div>
            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <td>カテゴリー:
                    <% if @post.category.present? %>
                      <%= @post.category %>
                    <% else %>
                      選択されていません
                    <% end %>
                  </td>
                </tr>
                <tr>
                  <td><%= simple_format @post.body %></td>
                </tr>
                <tr>
                  <td><time><%= @post.updated_at.strftime("%Y年-%m月-%d日 %H:%M") %></time></td>
                </tr>
              </table>
              <div id="favorites_buttons<%= @post.id %>">
                <%= render partial: "favorites/favorite", post: @post, favorite: @favorite %>
              </div>
              <% if user_signed_in? %>
                <% if @post.user.id == current_user.id %>
                  <%= link_to "編集", edit_post_path(@post), class: "button is-success" %>
                  <%= link_to "削除", post_path(@post), method: :delete, class: "button is-danger" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="columns">
    <div class="column is-4">
      <article class="panel is-link">
        <p class="panel-heading">
          By <%= @post.user.username %>
        </p>
        <%= link_to user_path(@post.user), class: "panel-block" do %>
          <span class="panel-icon">
            <i class="fas fa-user" aria-hidden="true"></i>
          </span>
          <%= @post.user.username %> のページへ
        <% end %>
      </article>
    </div>
    </div>
  </div>
</section>