config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  
  root to: "home#index"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    member do
      get :followings, :followers, :similar_users
    end
  end
  
  resources :posts do
    resources :favorites, only: [:create, :destroy]
  end
  
  resources :favorites, only: [:index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WearApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/d043ba00c4.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
    
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-info">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="notification is-danger">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>
      
    <nav class="navbar has-background-grey-dark" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <% if user_signed_in? %>
          <%= link_to user_path(current_user.id), class: "navbar-item" do %>
            <h1 class="title is-4" style="font-family: fantasy;">VINTAGE HOLIC</h1>
          <% end %>
        <% else %>
          <%= link_to root_path, class: "navbar-item" do %>
            <h1 class="title is-4" style="font-family: fantasy;">VINTAGE HOLIC</h1>
          <% end %>
        <% end %>
    
        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>
    
      <div id="navbarBasicExample" class="navbar-menu has-background-grey-dark">
        <div class="navbar has-background-grey-dark">
          <div class="navbar-item">
            <%= link_to "投稿一覧", posts_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "ユーザー一覧", users_path, class: "button is-warning is-light" %>
          </div>
        <% if user_signed_in? %>
          <div class="navbar-item">
            <%= link_to "新規投稿", new_post_path, class: "navbar-item button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "マイページ", user_path(current_user), class: "button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "button is-warning is-light" %>
          </div>
        <% else %>
          <div class="navbar-item">
            <%= link_to "ログイン", new_user_session_path, class: "button is-warning is-light" %>
          </div>
          <div class="navbar-item">
            <%= link_to "新規登録", new_user_registration_path, class: "button is-warning is-light" %>
           </div>
        <% end %>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>